on: [push, pull_request]
name: Check

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.27.1
          cache: true

      - name: Configure unprivileged ICMP
        run: |
          sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"
          sysctl net.ipv4.ping_group_range

      - name: Test
        run: make test
