on: [push, pull_request]
name: Check

jobs:
  check:
    strategy:
      matrix:
        go-version: [1.26.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Configure unprivileged ICMP
        if: runner.os == 'Linux'
        run: |
          sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"
          sysctl net.ipv4.ping_group_range

      - name: Test
        run: make test
